name: Build and Release Desktop Apps

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write # 赋予全局写权限，允许创建 Release 和上传 Assets

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest] # 移除 linux 以加快构建速度

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Vite App
        run: npm run build

      - name: Build & Publish Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Electron Builder 自动读取此 Token 上传到 Release
        run: npx electron-builder --publish always
